# -*- coding: utf-8 -*-
"""Initial Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhF6r9RkKtz8emBn54SSWw7DnRYMy9lM
"""

from google.colab import drive
drive.mount('/content/drive')
file = '/content/drive/MyDrive/MTH498 Project/Annual+DAF+Report+2025+Dataset.xlsx'

import pandas as pd
df = pd.read_excel(file)
df

# 'number_of_daf_accounts'
# 'total_daf_contributions'
# 'total_daf_grants'
# 'eoy_daf_assets'

df.boxplot(column=['total_daf_contributions', 'total_daf_grants', 'eoy_daf_assets'])

df.plot.scatter(
    x='total_daf_contributions',
    y='total_daf_grants'
)

num_col_list = ["ein","number_of_daf_accounts", "total_daf_contributions", "total_daf_grants", "eoy_daf_assets"]
num_df = df[num_col_list]

cln = num_df.dropna(subset=['number_of_daf_accounts'])
cln

cln2 = cln.drop_duplicates()
cln2

dupes = cln.duplicated()
dupes

duplicated_rows = cln[cln.duplicated(keep=False)]
duplicated_rows

"""There are some spots with duplicate-ish entries. They aren't actually duplicates, just places where the numerical entries are the same across multiple years."""

df_sorted = df.sort_values(['fiscal_year_end'], ascending=[1]) #1 means ascending, 0 means descending
df_sorted

filter_df1 = df.loc[(df["fiscal_year_end"] == 2019)]
filter_df1